# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Do the math
author: Giuseppe Lucarelli
email: giuseppelucarelli@pm.com
description: >- # this means to ignore newlines until "baseurl:"
  “The beauty of mathematics only shows itself to more patient followers.” - Maryam Mirzakhani
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# social links
github_username: giuluk
twitter_username: giuluk

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include: ['_pages']

### License
license: CC BY SA 4.0
license_url: https://creativecommons.org/licenses/by-sa/4.0/deed.it

header_pages:
  - _pages/blog.md
  - _pages/stuff.md
  - _pages/about.md
#  - _pages/categories.md
#  - _pages/tags.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
